// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "openapi": "3.0.3",
    "info": {
        "title": "Go Auth System API",
        "description": "Hệ thống xác thực chuẩn DDD, tích hợp Redis và PostgreSQL.",
        "version": "1.0.0",
        "contact": {
            "name": "Backend Team",
            "email": "support@yourdomain.com"
        }
    },
    "servers": [
        {
            "url": "http://localhost:8080/api/v1",
            "description": "Local Development"
        }
    ],
    "paths": {
        "/auth/login": {
            "post": {
                "tags": ["Authentication"],
                "summary": "Đăng nhập hệ thống",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": { "$ref": "#/components/schemas/LoginRequest" }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Thành công",
                        "content": {
                            "application/json": {
                                "schema": { "$ref": "#/components/schemas/APIResponse" }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "LoginRequest": {
                "type": "object",
                "properties": {
                    "email": { "type": "string", "format": "email" },
                    "password": { "type": "string", "minLength": 6 }
                }
            },
            "APIResponse": {
                "type": "object",
                "properties": {
                    "is_success": { "type": "boolean" },
                    "message": { "type": "string" },
                    "data": { "type": "object" }
                }
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Go Auth System API",
	Description:      "Hệ thống xác thực chuẩn DDD.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
